---
- hosts: localhost
  connection: local
  tasks:
    - name: Remove Service
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Service
        namespace: default
        name: led-monitoring
    - name: Remove Deployment
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Deployment
        namespace: default
        name: led-monitoring
    - name: Remove ServiceMonitor
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: ServiceMonitor
        namespace: monitoring
        name: led-monitoring